language: java
jdk:
  - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
  # Maven 3.0.5 official hack
  - "wget http://apache.mirror.iphh.net/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz && tar xfz apache-maven-3.0.5-bin.tar.gz && sudo mv apache-maven-3.0.5 /usr/local/maven-3.0.5 && sudo rm -f /usr/local/maven && sudo ln -s /usr/local/maven-3.0.5 /usr/local/maven"  
script: mvn clean install 
after_failure: "cat /home/travis/build/bmaggi/org.eclipse.papyrus.onefile.rcptt.tests/target/results/aut-console-0_console.log"